# Generated by Django 2.1.3 on 2018-11-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='food', max_length=128),
        ),
        migrations.AlterField(
            model_name='food',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='static/food_pics/'),
        ),
    ]
